//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberattendance
    {
        public int attendanceid { get; set; }
        public int membershipid { get; set; }
        public int scanid { get; set; }
        public string direction { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual membership membership { get; set; }
    }
}
