//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        public membership()
        {
            this.memberattendances = new HashSet<memberattendance>();
        }
    
        public int membershipid { get; set; }
        public int clubid { get; set; }
        public int scanid { get; set; }
        public string first { get; set; }
        public string middle { get; set; }
        public string last { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string countrycode { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string stateprov { get; set; }
        public string zip { get; set; }
        public string imagepath { get; set; }
        public Nullable<System.DateTime> applicationdate { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<System.DateTime> expirationdate { get; set; }
        public string email { get; set; }
    
        public virtual club club { get; set; }
        public virtual ICollection<memberattendance> memberattendances { get; set; }
    }
}
