//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class picklist
    {
        public int picklistid { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string value { get; set; }
    }
}
