//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class scandata
    {
        public int scandataid { get; set; }
        public int clubid { get; set; }
        public string documentid { get; set; }
        public string documenttype { get; set; }
        public string first { get; set; }
        public string middle { get; set; }
        public string last { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string countrycode { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string address { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string stateprov { get; set; }
        public string zip { get; set; }
        public string imagepath { get; set; }
        public Nullable<System.DateTime> creatdate { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
    
        public virtual club club { get; set; }
    }
}
