//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class scantag
    {
        public int scantagid { get; set; }
        public int tagid { get; set; }
        public int scanid { get; set; }
        public int clubid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
    }
}
