//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public int tagid { get; set; }
        public Nullable<int> clubid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creatdate { get; set; }
    }
}
