//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDScan.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership
    {
        public int membershipid { get; set; }
        public int clubid { get; set; }
        public Nullable<int> scanid { get; set; }
        public string palmscanid { get; set; }
        public Nullable<int> statusid { get; set; }
        public string first { get; set; }
        public string middle { get; set; }
        public string last { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string countrycode { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string stateprov { get; set; }
        public string zip { get; set; }
        public string imagepath { get; set; }
        public Nullable<System.DateTime> applicationdate { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
        public Nullable<System.DateTime> expirationdate { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public string email { get; set; }
        public string documentid { get; set; }
        public string documenttype { get; set; }
        public byte[] bio_palm_id { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> renewdate { get; set; }
    
        public virtual club club { get; set; }
    }
}
